_posts/2016-08-16-new-arfc-members.markdown
Hi there! I'd like to add this post (set to publish on August 16, 2016) announcing that so many of you have chosen to join ARFC. 
@lindsayad @andrewryh @radioactivekate @mworley2 :  please let me know (ideally as inline comments, a pull request, or comments in this github issue) before the evening of August 15th if you have any changes, corrections, deletions, or additions that you would like to make to this post.
I'm excited you'll all be joining ARFC. I'll contact you all soon to arrange our first research group meeting.
=> adds new member post

Rakefile
I believe this would close issue #3, but please review.
=> In Rakefile, push changes to source branch as well as master.

_posts/2017-02-01-mummah-wins-awards.markdown
@nuclearkatie ... are you ok with this blog post? Also -- congrats! I saw the Knights of St. Patrick decorations this morning. 
If this text is ok, please let me know and I'll push it. If not, just let me know and we'll either change or delete it -- up to you!!
=> @nuclearkatie, congratulations! can you review?

_data/research.yml
=> software link

manual/guides/guides.md
In response to #36 .
Add proxy bookmarklet to getting started guide
=> Add proxy bookmarklet to getting started guide

index.html
=> fix footer links

software/moltres/moltres.md, software/moltres/wiki/input_example.md
- Describe how tuning different input parameters can affect the output
- Note the existence of example output to compare against
- Also change "Doxygen" to "API" and move into development section of `moltres.md`
=> Moltres input-output walkthrough

_bibliography/references.bib
#57 
is this the right way to do it?
I feel like this is too simple of a solution, but it's the only .bib file I found.
=> new bibfile

_data/alumni.yml, _data/people.yml
=>  moves gavin and daniel to the past

_data/projects.yml
Link to Moltres info page fixed.
- Issue: #
- Dev: @
=> Dead link to Moltres web-page fixed

_data/people.yml
I put the picture and info for Anna Balla on the website. 
- Issue: #121
- Dev: @
=> Adding Anna to the Website

_data/people.yml
Updated my bio for the website to reflect a change in status. research asst --> graduate research asst.
=> updated bio

_data/people.yml
modified people.yml and added photo to img/people
- Issue: #
- Dev: @
=> modified people.yml and added photo to img/people

manual/guides/writing.md
This pull request adds some recommended practices for making writing a daily habit in ``writing.md``. 
- Issue: #
- Dev: @
=> adds writing habit recommendation

manual/guides/guides.md, manual/guides/pyne.md
This PR adds a page to the website that provides basic information on PyNE, as well as many links to various parts of the main PyNE website for installing and developing PyNE.
- Issue: #177
=> Adding a page to the Guides about PyNE

manual/guides/courses.md, manual/guides/guides.md
This PR adds a page to the website that provides basic information on course registration, which has information for both undergrads and grads.
- Issue: #173
=> Adding a page to the Guides about Courses

.github/pull_request_template.md
This will add an extra few lines to the PR Template with a link to the PR Review Template.
- Issue: #185 
Reviewers should use [this link](/manual/guides/pull_requests) to
get to the Review Checklist before they begin their review.
=> Adds a link for reviewers in the PR Template to the PR Review Checklist

manual/guides/writing/conf-poster.md
This PR adds a link to the LaTex poster template for conference posters, and adds a link to the writing checklist.
- Issue: #160 
- Dev: @
=> Add a links to the writing page for conference posters

manual/guides/writing/checklist.md
This PR resolves issue 193 and updates the writing checklist based on previously edited documents.
- Issue: #193 
Reviewers should use [this link](/manual/guides/pull_requests) to get to the Review Checklist before they begin their review.
=> Updating the Writing Checklist

software/moltres/wiki/input_example.md
There are two instances of "molten" in arfc.github.io/software/moltres/wiki/input_example.md that are spelled "molton"
- Issue: fix #202
=> Fixed typos ('molton' -> 'molten')

_data/alumni.yml, _data/people.yml
Add Anna Balla to People Page, Remove Anna Balla from Alumni Page
- Issue: #
- Dev: @
=> Add Anna Balla to People

software/moltres/moltres.md, software/moltres/wiki/input_example.md, software/moltres/wiki/wiki.md
This is an update to the links provided on the website. They should now navigate to the relevant locations.
- Issue: #206 
=> Updated the links to navigate to the proper locations.

manual/guides/dualboot.md, manual/guides/guides.md
This pull request adds a page that describes the process of dual booting, and guides readers to helpful resources.
- Issue: #
- Dev: @
=> adds guide for dual booting

manual/guides/blue_waters.md
There are a few minor changes to the Blue Waters guide on the arfc website. These include fixing the location of the group, links, and an extra added tip about running jobs.
- Issue: #216 
Reviewers should use [this link](http://arfc.github.io/manual/guides/pull_requests) to get to the 
=> Updates to Blue Waters guide on website

_data/alumni.yml, _data/people.yml
Removed Andrei from Current members and added to Alumni.
- Issue: #
- Dev: @
=> Andrei removed from People and added to Alumni

software/moltres/wiki/input_example.md, software/moltres/wiki/recommended.md, software/moltres/wiki/wiki.md
Closes #219 
This PR adds a webpage in the Moltres wiki on some recommended `Executioner` and `Preconditioning` settings, namely the solve type, automatic scaling parameter, time integration scheme, and preconditioning. These instructions are intended for new Moltres users who already have basic proficiency in MOOSE.
- Issue: #219 
=> Preconditioner guide

manual/guides/blue_waters.md
Added information on using Serpent in Blue Waters to guide.
- Issue: #216 
- Dev: @munkm 
=> Serpent Usage Information Added to Blue Waters Guide

_data/people.yml
This PR adds a link to @yardasol 's GitHub page.
- Dev: @munkm 
=> Add @yardasol GitHub link

software/moltres/moltres.md
This PR updates broken links, installation instructions, and contact information on the moltres webpage.
- Issue: arfc/moltres#187
- Dev: @
=> Update moltres contact

manual/guides/writing/presentation.md
This PR adds information to the guide for presentations about writing, presenting, and reviewing in the style of the report guide. It also adds some useful links about animations and buttons.
- Issue: closes #251  
=> Add presentation guidelines

_data/people.yml
This PR fixes a typo in @GabePaciocco's `people.yml` entry.
- Issue: none
- Dev: @munkm 
=> Fix typo in Gabriele Paciocco's `people.yml` entry

manual/guides/writing/checklist.md
This PR rearranges the checklist to have lists of actionable items and then sections for grammar, style, and advice on clarity. It also adds grammar rules for punctuation around quotations (lines 81 and 82) and about the prepositions 'of' and 'for' (line 90). Other than those specific lines, I didn't add anything new.
- Issue: #
- Closes: #260 
- Dev: @
Review the Checklist before they begin their review.
=> rearrange the checklist into actionable items and advice sections

.github/pull_request_template.md
closes #234 
Fixed the link to the Pull Request Guide.
- Dev: @
=> fix PR guide link

_data/alumni.yml, _data/people.yml
This PR moves some folks who are no longer active in the group anymore to the Alumni page.
- Dev: @nsryan2 
=> Update Alumni List

_data/alumni.yml, _data/people.yml
=> updates people and alumni

_data/people.yml
This PR updates Nathan Ryan's bio to more accurately reflect his work, and changes the link for his personal site to the current (hopefully final) address.
=> update nsryan's bio and personal website

_data/people.yml
Originally was accessing fisherr.png; should have accessed fisherr.jpg
=> Fixed Riley's picture

_data/alumni.yml, _data/people.yml
Moves @abachma2 from "People" to "Alumni."
=> moves amanda to alumni

manual/guides/guides.md
The previous link lead to a 'page not found', this PR fixes this issue and leads to the correct site. 
- [ x] Bug fix (non-breaking change which fixes an issue)
- Issue: #
- Dev: @
=> Fixing borken 'Configure git' Link, addressing issue #285

manual/guides/guides.md
Updates the link to the ECIP book. 
- Issue: #304 
- Dev: @osanstrong
=> updates link from old one which is dead to new one on i-share

manual/guides/writing/checklist.md
The word significant offers judgement when used outside the context of statistical significance. The writing course emphasizes this point and the current arfc writing checklist omits it.
- Issue: #
- Dev: @nsryan2 
=> Additional point under Enhancing Clarity

_data/positions.yml
Moves the most recent postdoc opening to "closed" status so that it will no longer appear on the live site. 
=> postdoc position is closed

.github/workflows/deploy-site.yml
=> reverts last change to bundler cache #361

manual/guides/getting_serpent_license.md
The 'Acquiring a Serpent License' guide is outdated. This PR updates the guide to reflect the changes to the application process. Resolves #335.
- Issue: #335 
- Dev: @nsryan2 
=> Update 'Acquiring a Serpent License' Guide

_data/alumni.yml, _data/people.yml
Riley Fisher graduated and no longer works here. I have moved him to the alumni page.
Edit from Nathan: Closes #334 
- Dev: @rileyf2 
=> Moves Riley to Alumni Page

manual/guides/writing.md
This PR closes #248 by adding a new sub section to the [Writing Resources](https://arfc.github.io/manual/guides/writing/) page that links to the [CRediT taxonomy](https://credit.niso.org/).  
- Issue: #248 
- Dev: @munkm 
=> Add link to CRediT taxonomy for authorship and acknowledgements

manual/guides/travel.md
This PR fixes a small error with a link in the travel guide.
=> fix hyperlink in travel guide

manual/guides/writing/checklist.md
In group meeting, we noticed that there is a missing `\nonumber` in the example equation. This PR adds it.
- Issue: #
=> Add nonumber to checklist equation

manual/guides/guides.md, manual/guides/plots.md
This PR creates a new guide on plotting and adds it to the writing section of [guides](https://arfc.github.io/manual/guides/). This page links to a [gist](https://gist.github.com/nsryan2/456490df118ab3318ec07c7610432e69) I made for a `.mplstyle` file and has general advice on colors, fonts, markers/line styles, plot size, and an example using the style file.
This pr closes #395 
- Issue: #395
- Dev: @ZoeRichter 
=> Create plotting file and update guides page

manual/guides/writing/conf-abs.md, manual/guides/writing/journal-article.md
In group meeting we found some wonky list formatting in two writing guides on the [conf-abs](https://arfc.github.io/manual/guides/writing/conf-abs/) and [journal-article](https://arfc.github.io/manual/guides/writing/journal-article) pages. This PR emulates the format of the other writing guides.
- Issue: # n/a
=> Remove - [ ] structure from journal and conference abstract writing pages

manual/guides/travel.md
Changes include minor fixes to the travel guide:
1. List numbering fixed
2. Typo "accessin" changed to "access in"
3. Added Jeni Lamb to the list of people to add (and a link to the directory)
- Issue: #
- Dev: @
=> Travel update and minor fixes

manual/guides/guides.md, manual/guides/katy/codereq.md, manual/guides/katy/commreq.md, manual/guides/katy/meeting.md, manual/guides/katy/recreq.md, manual/guides/software_templates.md, manual/guides/writing/dissertation.md, manual/guides/writing/ms-thesis.md, manual/guides/writing/prelim.md
Made a bunch of updates to the guides to bring us into 2025. 
=> 2025 updates
